title: "Arati Chattopadhyay"
description: "Official Website of Author Arati Chattopadhyay"
baseurl: "" # if using GitHub Pages with custom domain leave empty
url: "https://yourusername.github.io" # change to custom domain later

author:
  name: "Arati Chattopadhyay"
  bio: "Author, storyteller, and chronicler of memories."
  email: "your@email.com"

# Collections
collections:
  works:
    output: true
  memories:
    output: true

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Arati Chattopadhyay"
  - scope:
      path: ""
      type: "works"
    values:
      layout: work
  - scope:
      path: ""
      type: "memories"
    values:
      layout: memory
